name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Visualize softuni username
      run: echo "danieibogdanov"

  run_ui_tests:
    runs-on: ubuntu-latest
    needs: run_unit_tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Start application
      run: npm start &
    - name: Install playwright dependencies
      run: npx playwright install
    - name: Run ui tests
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: run_ui_tests
    steps:
        - uses: actions/checkout@v4
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true
